
name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main  # or change to "master" if that's your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"  # replace with your Flutter version if different

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
